/**
 * Seed Demo Teachers for Find Teacher Page
 * Inserts 10 diverse demo teachers into Supabase
 */

// Subject IDs from Supabase
const SUBJECTS = {
  Mathematics: '9454395b-727c-4c63-8c5c-854863ce2fb8',
  English: 'dfcaf6f0-f776-4ba8-91dc-3003d41495e2',
  Physics: '68b4c1c0-6500-4085-a775-165ede080d33',
  Chemistry: 'a939cd4b-8389-40e4-9cec-8c0d08ec23cd',
  Literature: '5f00ab55-39f0-446d-ae1f-9c04ae03bbe6',
  Biology: 'e89dedfa-fcb5-4593-8df1-64349a84a634',
};

// Demo teachers data
const DEMO_TEACHERS = [
  {
    name: 'Nguyễn Thị Lan',
    email: 'nguyen.lan.demo@tuto.vn',
    phone: '+84901234567',
    avatar: 'https://ui-avatars.com/api/?name=Nguyen+Lan&background=0B5FFF&color=fff&size=128',
    qualifications: 'Thạc sĩ Toán học, Đại học Quốc gia Hà Nội',
    experience: 8,
    hourly_rate: 350,
    rating: 4.8,
    review_count: 127,
    description: 'Giáo viên Toán với 8 năm kinh nghiệm, chuyên luyện thi đại học và bồi dưỡng học sinh giỏi.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận 1, TP. Hồ Chí Minh',
    latitude: 10.7769,
    longitude: 106.7009,
    subjects: [SUBJECTS.Mathematics],
  },
  {
    name: 'Trần Văn Minh',
    email: 'tran.minh.demo@tuto.vn',
    phone: '+84901234568',
    avatar: 'https://ui-avatars.com/api/?name=Tran+Minh&background=10B981&color=fff&size=128',
    qualifications: 'Cử nhân Tiếng Anh, Đại học Ngoại ngữ',
    experience: 5,
    hourly_rate: 300,
    rating: 4.6,
    review_count: 89,
    description: 'Giáo viên Tiếng Anh chuyên luyện thi IELTS và giao tiếp, phương pháp hiện đại, dễ hiểu.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận Ba Đình, Hà Nội',
    latitude: 21.0285,
    longitude: 105.8542,
    subjects: [SUBJECTS.English],
  },
  {
    name: 'Lê Thị Hương',
    email: 'le.huong.demo@tuto.vn',
    phone: '+84901234569',
    avatar: 'https://ui-avatars.com/api/?name=Le+Huong&background=F59E0B&color=fff&size=128',
    qualifications: 'Thạc sĩ Vật lý, Đại học Bách khoa',
    experience: 12,
    hourly_rate: 450,
    rating: 4.9,
    review_count: 203,
    description: 'Giáo viên Vật lý với 12 năm kinh nghiệm, từng đào tạo nhiều học sinh đạt giải quốc gia.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận 3, TP. Hồ Chí Minh',
    latitude: 10.7830,
    longitude: 106.6967,
    subjects: [SUBJECTS.Physics],
  },
  {
    name: 'Phạm Đức Anh',
    email: 'pham.anh.demo@tuto.vn',
    phone: '+84901234570',
    avatar: 'https://ui-avatars.com/api/?name=Pham+Anh&background=EF4444&color=fff&size=128',
    qualifications: 'Tiến sĩ Hóa học, Đại học Khoa học Tự nhiên',
    experience: 15,
    hourly_rate: 500,
    rating: 5.0,
    review_count: 156,
    description: 'Giáo viên Hóa học hàng đầu, chuyên luyện thi đại học và Olympic quốc tế.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận Cầu Giấy, Hà Nội',
    latitude: 21.0308,
    longitude: 105.8022,
    subjects: [SUBJECTS.Chemistry],
  },
  {
    name: 'Hoàng Thị Mai',
    email: 'hoang.mai.demo@tuto.vn',
    phone: '+84901234571',
    avatar: 'https://ui-avatars.com/api/?name=Hoang+Mai&background=8B5CF6&color=fff&size=128',
    qualifications: 'Thạc sĩ Ngữ văn, Đại học Sư phạm',
    experience: 7,
    hourly_rate: 280,
    rating: 4.7,
    review_count: 94,
    description: 'Giáo viên Văn học với phương pháp dạy sáng tạo, giúp học sinh yêu thích môn Văn.',
    languages: ['Vietnamese'],
    address: 'Quận 7, TP. Hồ Chí Minh',
    latitude: 10.7314,
    longitude: 106.7214,
    subjects: [SUBJECTS.Literature],
  },
  {
    name: 'Vũ Minh Tuấn',
    email: 'vu.tuan.demo@tuto.vn',
    phone: '+84901234572',
    avatar: 'https://ui-avatars.com/api/?name=Vu+Tuan&background=06B6D4&color=fff&size=128',
    qualifications: 'Cử nhân Sinh học, Đại học Y Dược',
    experience: 6,
    hourly_rate: 320,
    rating: 4.5,
    review_count: 67,
    description: 'Giáo viên Sinh học chuyên luyện thi đại học khối B, phương pháp dễ nhớ, dễ hiểu.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận Đống Đa, Hà Nội',
    latitude: 21.0188,
    longitude: 105.8294,
    subjects: [SUBJECTS.Biology],
  },
  {
    name: 'Đỗ Thị Linh',
    email: 'do.linh.demo@tuto.vn',
    phone: '+84901234573',
    avatar: 'https://ui-avatars.com/api/?name=Do+Linh&background=EC4899&color=fff&size=128',
    qualifications: 'Thạc sĩ Toán học, Đại học Sư phạm',
    experience: 10,
    hourly_rate: 380,
    rating: 4.8,
    review_count: 145,
    description: 'Giáo viên Toán với 10 năm kinh nghiệm, chuyên dạy Toán cấp 2 và luyện thi vào 10.',
    languages: ['Vietnamese'],
    address: 'Quận 2, TP. Hồ Chí Minh',
    latitude: 10.7870,
    longitude: 106.7493,
    subjects: [SUBJECTS.Mathematics],
  },
  {
    name: 'Bùi Văn Hùng',
    email: 'bui.hung.demo@tuto.vn',
    phone: '+84901234574',
    avatar: 'https://ui-avatars.com/api/?name=Bui+Hung&background=14B8A6&color=fff&size=128',
    qualifications: 'Cử nhân Tiếng Anh, Đại học Hà Nội',
    experience: 4,
    hourly_rate: 250,
    rating: 4.4,
    review_count: 52,
    description: 'Giáo viên Tiếng Anh trẻ, năng động, chuyên dạy giao tiếp và phát âm chuẩn.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận Tân Bình, TP. Hồ Chí Minh',
    latitude: 10.8014,
    longitude: 106.6526,
    subjects: [SUBJECTS.English],
  },
  {
    name: 'Ngô Thị Hoa',
    email: 'ngo.hoa.demo@tuto.vn',
    phone: '+84901234575',
    avatar: 'https://ui-avatars.com/api/?name=Ngo+Hoa&background=F97316&color=fff&size=128',
    qualifications: 'Thạc sĩ Vật lý, Đại học Khoa học Tự nhiên',
    experience: 9,
    hourly_rate: 400,
    rating: 4.7,
    review_count: 118,
    description: 'Giáo viên Vật lý với phương pháp dạy thực nghiệm, giúp học sinh hiểu sâu bản chất.',
    languages: ['Vietnamese', 'English'],
    address: 'Quận Hoàn Kiếm, Hà Nội',
    latitude: 21.0285,
    longitude: 105.8542,
    subjects: [SUBJECTS.Physics],
  },
  {
    name: 'Lý Văn Đức',
    email: 'ly.duc.demo@tuto.vn',
    phone: '+84901234576',
    avatar: 'https://ui-avatars.com/api/?name=Ly+Duc&background=6366F1&color=fff&size=128',
    qualifications: 'Cử nhân Hóa học, Đại học Bách khoa',
    experience: 3,
    hourly_rate: 220,
    rating: 4.3,
    review_count: 38,
    description: 'Giáo viên Hóa học trẻ, nhiệt tình, chuyên dạy Hóa cấp 2 và luyện thi vào 10.',
    languages: ['Vietnamese'],
    address: 'Quận 5, TP. Hồ Chí Minh',
    latitude: 10.7553,
    longitude: 106.6670,
    subjects: [SUBJECTS.Chemistry],
  },
];

// Note: This script is for reference. Actual seeding will be done via Supabase MCP tools.
console.log('Demo teachers data prepared. Use Supabase MCP to insert.');

